## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [1]:
import pandas as pd

In [19]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
data.shape

(32561, 15)

In [71]:
data.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [5]:
print(data['sex'].value_counts())

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [16]:
avg_age = data.groupby('sex')['age'].mean()
print("Men average age:", avg_age.loc['Male'].round(1))

Men average age: 39.4

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [18]:
usa_native = data['native-country'].value_counts().loc['United-States']
print("Percantage of USA peolpe:", round(usa_native / data.shape[0] * 100, 2) )

Percantage of USA peolpe: 89.59

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [27]:
lower_salary = data[data['salary'] == '<=50K']
print("Mean age of lower salary group:", lower_salary['age'].mean().round(2))
print("Standart deviation:", lower_salary['age'].std().round(2))

Mean age of lower salary group: 36.78
Standart deviation: 14.02

In [28]:
higher_salary = data[data['salary'] == '>50K']
print("Mean age of higher salary group:", higher_salary['age'].mean().round(2))
print("Standart deviation:", higher_salary['age'].std().round(2))

Mean age of higher salary group: 44.25
Standart deviation: 10.52

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [33]:
is_true = higher_salary['education'].isin(['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']).all()
print(f"All rich people have higher education: {is_true}")

All rich people have higher education: False

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [41]:
info = data.groupby(['race', 'sex'])['age'].describe().round(2)
info

                             count   mean    std   min   25%   50%    75%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.12  13.11  17.0  27.0  36.0  46.00
                   Male      192.0  37.21  12.05  17.0  28.0  35.0  45.00
Asian-Pac-Islander Female    346.0  35.09  12.30  17.0  25.0  33.0  43.75
                   Male      693.0  39.07  12.88  18.0  29.0  37.0  46.00
Black              Female   1555.0  37.85  12.64  17.0  28.0  37.0  46.00
                   Male     1569.0  37.68  12.88  17.0  27.0  36.0  46.00
Other              Female    109.0  31.68  11.63  17.0  23.0  29.0  39.00
                   Male      162.0  34.65  11.36  17.0  26.0  32.0  42.00
White              Female   8642.0  36.81  14.33  17.0  25.0  35.0  46.00
                   Male    19174.0  39.65  13.44  17.0  29.0  38.0  49.00

                            max
race               sex
Amer-Indian-Eskimo Female  80.0
                   Male    82.0
Asian-Pac-Islander Female  75.0
                   Male    90.0
Black              Female  90.0
                   Male    90.0
Other              Female  74.0
                   Male    77.0
White              Female  90.0
                   Male    90.0

In [42]:
print("Highest age of male Asian-Pac-Islander:", info.loc[('Asian-Pac-Islander', 'Male'), 'max'])

Highest age of male Asian-Pac-Islander: 90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [43]:
higher_salary.shape

(7841, 15)

In [53]:
married = data[data['marital-status'].str[:7] == 'Married']
not_married = data[data['marital-status'].str[:7] != 'Married']

In [55]:
print('Married people with high salary:', round( married[married['salary'] == '>50K'].shape[0] / married.shape[0] * 100 , 2))
print('Not married people with high salary:', round( not_married[not_married['salary'] == '>50K'].shape[0] / not_married.shape[0] * 100 , 2))

Married people with high salary: 43.69
Not married people with high salary: 6.45

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [ ]:
max_hours_per_week = data['hours-per-week'].max()
data[(data['hours-per-week'] == max_hours_per_week.astype(int))]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
935,37,Private,176900,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,99,United-States,>50K
1172,25,Private,404616,Masters,14,Married-civ-spouse,Farming-fishing,Not-in-family,White,Male,0,0,99,United-States,>50K
1887,55,Self-emp-not-inc,184425,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,99,United-States,>50K
3578,37,Self-emp-inc,382802,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,99,United-States,>50K
4086,50,?,174964,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,99,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30992,40,Self-emp-inc,104235,Masters,14,Never-married,Other-service,Own-child,White,Male,0,0,99,United-States,<=50K
31681,43,Private,266324,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1902,99,United-States,>50K
31699,43,Self-emp-not-inc,163108,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,99,United-States,<=50K
32469,58,Self-emp-inc,181974,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,?,<=50K
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K

In [73]:
max_hours_per_week = data['hours-per-week'].max()
number_of_people = data[data['hours-per-week'] == max_hours_per_week].shape[0]
print('Max hours per week:', max_hours_per_week)
print(f'Number of people working {max_hours_per_week} hours per week: {number_of_people}')
print('Percantage of those who is paid high:', round(data[(data['hours-per-week'] == max_hours_per_week.astype(int)) & (data['salary'] == '>50K')].shape[0] / number_of_people * 100, 2))

Max hours per week: 99
Number of people working 99 hours per week: 85
Percantage of those who is paid high: 29.41

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [75]:
higher_salary.groupby('native-country')['hours-per-week'].mean().round(2)

native-country
?                     45.55
Cambodia              40.00
Canada                45.64
China                 38.90
Columbia              50.00
Cuba                  42.44
Dominican-Republic    47.00
Ecuador               48.75
El-Salvador           45.00
England               44.53
France                50.75
Germany               44.98
Greece                50.62
Guatemala             36.67
Haiti                 42.75
Honduras              60.00
Hong                  45.00
Hungary               50.00
India                 46.48
Iran                  47.50
Ireland               48.00
Italy                 45.40
Jamaica               41.10
Japan                 47.96
Laos                  40.00
Mexico                46.58
Nicaragua             37.50
Peru                  40.00
Philippines           43.03
Poland                39.00
Portugal              41.50
Puerto-Rico           39.42
Scotland              46.67
South                 51.44
Taiwan                46.80
Thailand              58.33
Trinadad&Tobago       40.00
United-States         45.51
Vietnam               39.20
Yugoslavia            49.50
Name: hours-per-week, dtype: float64

In [76]:
lower_salary.groupby('native-country')['hours-per-week'].mean().round(2)

native-country
?                             40.16
Cambodia                      41.42
Canada                        37.91
China                         37.38
Columbia                      38.68
Cuba                          37.99
Dominican-Republic            42.34
Ecuador                       38.04
El-Salvador                   36.03
England                       40.48
France                        41.06
Germany                       39.14
Greece                        41.81
Guatemala                     39.36
Haiti                         36.33
Holand-Netherlands            40.00
Honduras                      34.33
Hong                          39.14
Hungary                       31.30
India                         38.23
Iran                          41.44
Ireland                       40.95
Italy                         39.62
Jamaica                       38.24
Japan                         41.00
Laos                          40.38
Mexico                        40.00
Nicaragua                     36.09
Outlying-US(Guam-USVI-etc)    41.86
Peru                          35.07
Philippines                   38.07
Poland                        38.17
Portugal                      41.94
Puerto-Rico                   38.47
Scotland                      39.44
South                         40.16
Taiwan                        33.77
Thailand                      42.87
Trinadad&Tobago               37.06
United-States                 38.80
Vietnam                       37.19
Yugoslavia                    41.60
Name: hours-per-week, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [88]:
def age_status(age):
    if 16 <= age < 35:
        return 'young'
    elif 35 <= age < 70:
        return 'adult'
    elif 70 <= age < 100:
        return 'retiree'
    else:
        'undefined status'

data['AgeGroup'] = data['age'].apply(age_status)
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [91]:
grouped_age_category = data[data['salary'] == '>50K'].groupby('AgeGroup').agg(Number=('age', 'count'))
grouped_age_category

          Number
AgeGroup
adult       6240
retiree      113
young       1488

In [99]:
row = grouped_age_category.loc[grouped_age_category['Number'].idxmax()]
print(f'Age group with the highest numberof high salary: {row.name} {row["Number"]}')

Age group with the highest numberof high salary: adult 6240

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

Вариация задания:
Сгруппировать тех людей по признаку occupation, которые отрабатывают более 5 часов в неделю. Посчитать их количество, средний возраст и вывести те группы, в которых средний возраст >40

In [103]:
occupation_grouped = data[data['hours-per-week'] > 5].groupby('occupation').agg(Num_category = ('age', 'count'), Avg_age = ('age', 'mean'))
occupation_grouped[occupation_grouped['Avg_age'] > 40].round(2)

                  Num_category  Avg_age
occupation
Exec-managerial           4052    42.11
Farming-fishing            993    41.18
Priv-house-serv            146    41.23
Prof-specialty            4114    40.51
Transport-moving          1596    40.18

Оригинальное задание:

In [104]:
occupation_grouped_2 = data.groupby('occupation').agg(Num_category = ('age', 'count'), Avg_age = ('age', 'mean'))
occupation_grouped_2

                   Num_category    Avg_age
occupation
?                          1843  40.882800
Adm-clerical               3770  36.964456
Armed-Forces                  9  30.222222
Craft-repair               4099  39.031471
Exec-managerial            4066  42.169208
Farming-fishing             994  41.211268
Handlers-cleaners          1370  32.165693
Machine-op-inspct          2002  37.715285
Other-service              3295  34.949621
Priv-house-serv             149  41.724832
Prof-specialty             4140  40.517633
Protective-serv             649  38.953775
Sales                      3650  37.353973
Tech-support                928  37.022629
Transport-moving           1597  40.197871

In [113]:
def filter_func(group):
    cond1 = group['age'].mean() <= 40
    cond2 = (group['hours-per-week'] > 5).all()
    print(cond1, cond2)
    return cond1 and cond2

filtered_data = data.groupby('occupation').filter(filter_func)
filtered_data

False False
True False
True True
True False
False False
False False
True False
True False
True False
False False
False False
True False
True False
True False
False False

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
442,24,Federal-gov,191073,HS-grad,9,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,<=50K,young
1300,29,Federal-gov,301010,Some-college,10,Never-married,Armed-Forces,Not-in-family,Black,Male,0,0,60,United-States,<=50K,young
14613,39,Federal-gov,227597,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,50,United-States,<=50K,adult
16111,24,Federal-gov,287988,Bachelors,13,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,40,United-States,<=50K,young
18034,34,Federal-gov,172716,12th,8,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,0,40,United-States,<=50K,young
18644,23,Federal-gov,163870,Some-college,10,Never-married,Armed-Forces,Other-relative,White,Male,0,0,40,United-States,<=50K,young
18769,30,Federal-gov,76313,HS-grad,9,Married-civ-spouse,Armed-Forces,Other-relative,Amer-Indian-Eskimo,Male,0,0,48,United-States,<=50K,young
25799,46,Federal-gov,344415,Masters,14,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,1887,40,United-States,>50K,adult
32316,23,Federal-gov,173851,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,8,United-States,<=50K,young

In [112]:
remaining_occupations = filtered_data['occupation'].unique()
print(f"Groups after filter: {remaining_occupations}")

Groups after filter: ['Armed-Forces']